"""Add last editor tracking to Notice and Event

Revision ID: c53c2cab1354
Revises: 1f335732472f
Create Date: 2025-04-10 03:29:28.400753

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c53c2cab1354'
down_revision = '1f335732472f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted with explicit FK names ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('last_edited_by_id', sa.Integer(), nullable=True)
        )
        batch_op.add_column(
            sa.Column('last_edited_timestamp', sa.DateTime(), nullable=True)
        )
        batch_op.create_foreign_key(
            'fk_event_last_edited_by_id_user',
            'user',
            ['last_edited_by_id'],
            ['id']
        )

    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('last_edited_by_id', sa.Integer(), nullable=True)
        )
        batch_op.add_column(
            sa.Column('last_edited_timestamp', sa.DateTime(), nullable=True)
        )
        batch_op.create_foreign_key(
            'fk_notice_last_edited_by_id_user',
            'user',
            ['last_edited_by_id'],
            ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted with explicit FK names ###
    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_notice_last_edited_by_id_user',
            type_='foreignkey'
        )
        batch_op.drop_column('last_edited_timestamp')
        batch_op.drop_column('last_edited_by_id')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_event_last_edited_by_id_user',
            type_='foreignkey'
        )
        batch_op.drop_column('last_edited_timestamp')
        batch_op.drop_column('last_edited_by_id')
    # ### end Alembic commands ###
